### ISSUE TITLE
invalid command name "::tincr::cache::get"

### ISSUE THREAD

**Issue by ttown523** [bradselw/tincr#10]
I get an error when executing the following tincr command in Vivado:

Vivado% ::tincr::bels::compatible_with_cell $cell
invalid command name "::tincr::cache::get"

I think that I have set up the tincr environment correctly since I can run several other commands, so I am not sure why this bug is occurring.

**Comment by bradselw** [comment]
Thanks ttown523, I have been able to repro this error. This is probably due to some recent refactoring in Tincr's caching mechanism. I should have a fix pushed to master shortly.

**Comment by bradselw** [comment]
This bug has been fixed. See instructions [here](https://github.com/bradselw/tincr/wiki/Forks#merging-an-upstream-repository-into-your-fork) for how to sync the update to your repo(s). A couple notes about the compatible_with_bels command:
- This cache hasn't been updated to save to disk yet (it's on my very long list of Tincr ToDos). That means it will have to generate the cache on the first call during each Vivado session, which can take several minutes. Subsequent calls to this cache are instantaneous.
- If you're working in an interactive Tcl prompt, Tcl will echo the result of the command to the console. It will take FOREVER to print thousands of objects to the console. To avoid this, append `; list` to the end of your commands.
