### ISSUE TITLE
Multiple IOB site names and inconsistency in XDLRC and placement.xdc files

### ISSUE THREAD

**Issue by nelsobe** [bradselw/tincr#14]
There is an issue with IOB site names.  In Vivado's Tcl, if I execute:

select_objects [get_sites IOB_X0Y78]   or
select_objects [get_sites N15]

it returns
         INFO: [Coretcl 2-12] 'IOB_X0Y78' selected.

in both cases.  Executing:

get_selected_objects

in either case returns a list of 2 items:   IOB_X0Y78 N15

Strangely in either case, the properties window (^E) it shows that the IOB is named N15 and that there is an "IOB alias" of IOB_X0Y78.  The get_selected_objects command would suggest there are 2 sites getting selected but the properties window would suggest that there is only one site and it has 2 names (a real name and an alias).

Where this bites us is that the XDLRC files generated by Tincr use the name N15 for the site name but the Tincr checkpoint file placement.xdc uses the name IOB_X0Y78 when specifying a LOC for a cell.  The name IOB_X0Y78 doesn't exist in the XDLRC file and so a placement error occurs when processing a checkpoint.

It would seem that the right thing to do would be to be consistent and either always use the pin name (N15) or the positional site name (IOB_X0Y78) for the site.  It probably doesn't matter but given a choice I would prefer the latter since that matches how all other sites are named.

Anyone else have any thoughts on this?

**Comment by bradselw** [comment]
What part are you using?

**Comment by bradselw** [comment]
So I dug into the code here, and it looks like this (using the package pin name) is the expected behavior for bonded IOBs:

```
    foreach site $sites {
        set state "internal"
        set name [get_property NAME $site]
        if {[get_property IS_PAD $site]} {
            if {[get_property IS_BONDED $site]} {
                set state "bonded"
                set name [get_property NAME [get_package_pins -quiet -of_object $site]]
            } else {
                set state "unbonded"
            }
        }
```

I've confirmed that this is the same as XDLRC files generated by xdl.exe.

I don't think that it is a good idea to deviate from parity with xdl.exe's XDLRC. We could talk about possibly changing how IOBs are identified in Tincr checkpoints. Also, I'd be interested to know how XDL identifies IOBs - whether it uses the pin name or positional site name.

**Comment by nelsobe** [comment]
After reading Brad's post, I think I agree that we do want to maintain parity with ISE's XDLRC (as long as we are using V7 we can continue to verify against it) and so should use the N15 style name everywhere.

**Comment by nelsobe** [comment]
I believe Thomas was going to propose a fix to the Tincr checkpoint writing code to use the N15 style names for bonded IO.  Has that been done yet and is it in the repository?

**Comment by bradselw** [comment]
I haven't seen anything yet. Should be a simple change though, so I'll
create a PR and you guys can take a look at it, see if it's what you need.

**Comment by bradselw** [comment]
I looked into this a little today and I wanted to touch base with you before I went any further with it. I ran the following tincr command on an xc7k70tfbg484 part:

``` tcl
tincr::lib_cells compatible_with [get_sites -of [get_package_pins]]
```

This returns all cell types (lib_cells) that can possibly be placed on a BEL in a package pin's site on that device. It returned four types: KEEPER, PULLDOWN, INV, and PULLUP. Are those the types of cells you guys are trying to place? I was under the impression that you were trying to place top-level ports? If ports, Vivado has a construct called a port that is a combination between a cell and a pin. It can be placed like a cell on a package pin, but connected to a net like a pin. Check out [tincr's ports ensemble](https://github.com/bradselw/tincr/blob/master/tincr/cad/design/ports.tcl) to see what I mean.

If ports are what you're interested in, then Tincr checkpoints already use package pins to identify their placement (i.e. N15-style).

**Comment by nelsobe** [comment]
The problem really is that there are lines like this in the placement.xdc file:

set_property LOC IOB_X0Y78 [get_cells {clk_IBUF_inst}]

There is no IOB_X0Y78 in the XDLRC file.  There is an R16 or whatever which maps to it, but no IOB_X0Y78.  Thus, any tools (like RS2) that only have the XDLRC file to go on (and not Vivado which understands that IOB_X0Y78 is an alias) will not be able to determine where to place clk_IBUF_inst.

Thomas is working a pull request which fixes this.  Let’s wait until he gets that done…
