### ISSUE TITLE
::tincr::write_xdlrc not printing tiles

### ISSUE THREAD

**Issue by mjc31511** [bradselw/tincr#35]
When I run the following command the resulting xdlrc file does not contain any tile information (it only contains primitive defs):

`::tincr::write_xdlrc -part [get_parts xc7a200tsbg484-1] -max_processes 1 -primitive_defs xc7a200tsbg484_full.xdlrc`

**Comment by bradselw** [comment]
Attempting a repro...

**Comment by bradselw** [comment]
I have the process running, and it appears to be working. @mjc31511 I have some follow-up questions:
- What environment are you running in? (Linux, Windows, x86, amd64, etc.)
- During the execution of the command (When it says "Percent complete:"), navigate to `<working directory>/.Tincr/xdlrc/xc7a200tsbg484-1` and try to open up one of the .dat files. Are you seeing tile information in there?

**Comment by ttown523** [comment]
Update on this: matthew changed the function call to:

`::tincr::write_xdlrc -part "xc7a200tsbg484" -max_processes 1 -primitive_defs xc7a200tsbg484_full.xdlrc`

and it worked. Is this expected?

**Comment by mjc31511** [comment]
I have been trying to get the behavior to manifest itself again. As thomas said I changed a few things and got my original command working. From what I can tell, I only notice the buggy behavior when I do not include the pkgIndex.tcl file in my `<Vivado Install Directory>\tps\tcl\tcl8.5` directory. I previously sourced the file directly from the command line (using the `source <tincr directory>\install\pkgIndex.tcl` command). To answer your previous questions I am running on Windows 10 64-bit and I do not see any data in the .dat files while the command is executing.

**Comment by bradselw** [comment]
I was able to reproduce this behavior when I removed pkgIndex.tcl from my Vivado installation.

Tincr expects the pkgIndex.tcl file to be copied to the `<Vivado Install Directory>\tps\tcl\tcl8.5` directory. If it is not, Tincr is not guaranteed to work. Please review Tincr's installation instructions on the [wiki](https://github.com/byuccl/tincr/wiki/Setup-Tincr) or in the [README](https://github.com/byuccl/tincr/blob/master/install/README.txt).

I am closing this issue as it is not currently a supported scenario. If you wish to make a feature request, please file another issue and label it as "enhancement". Thanks.
