### ISSUE TITLE
Update cellLibrary.xml

### ISSUE THREAD

**Issue by ttown523** [bradselw/tincr#44]
- The cellLibrary.xml needs to be updated to include the family for the cell library. The following element needs to be added: 

```
<family>ARTIX7</family>
<cells>
....
</cells>
```

- Also, all references to "primitive_type" need to be changed to "site_type." This is true for the familyInfo.xml as well.

**Comment by bradselw** [comment]
Is this issue resolved?

**Comment by DallonTG** [comment]
This issue is resolved.
