### ISSUE TITLE
ambiguous command name "get_design"

### ISSUE THREAD

**Issue by snx90** [bradselw/tincr#85]
Trying to reproduce the example in RapidSmith2 documentation (section 3), I got the following error when running tincr::write_rscp cordic:

```
Vivado% tincr::write_rscp cordic
Writing RapidSmith2 checkpoint to cordic.rscp...
EDIF Done...(0.076873s)
get_lib_cells: Time (s): cpu = 00:00:01 ; elapsed = 00:00:05 . Memory (MB): peak = 1462.191 ; gain = 0.000
Macros Done...(5.407799s)
XDC Done...(0.015345s)
invalid command name "get_design"
ambiguous command name "get_design": get_design_info get_designs
```

The resulting cordic.rscp folder contains the expected files but routing.rsc and the others are (almost) empty.

**Comment by DallonTG** [comment]
Thanks for reporting this bug! It only occurred when the tincr namespace was imported. Although the readme recommends importing the namespace, I personally don't. In any case, this issue has been fixed with #87.
