### ISSUE TITLE
Deprecated Commands

### ISSUE THREAD

**Issue by DallonTG** [bradselw/tincr#86]
Deprecated commands, such as "write_tcp", cause confusion for people starting out with Tincr and RapidSmith2. 

I think we should either entirely remove some of these deprecated commands or at least immediately print some sort of warning message when a user calls a deprecated command.

**Comment by nelsobe** [comment]
Agree completely.  With regards to RapidSmith2 issue #364, it only became clear this morning after his reply to my first question that he was using write_tcp (I didn't even realize that command was in the distribution).

**Comment by DallonTG** [comment]
Should we just delete the Tincr IO procedures that are deprecated? I don't see any reason for them to stay.

**Comment by nelsobe** [comment]
I believe we should.
